version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres       
      POSTGRES_PASSWORD: postgres   
      POSTGRES_DB: volga            
    ports:
      - "5432:5432"                 
    volumes:
      - postgres_data_test5:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - work

  account_service:
    build:
      context: ./account/
    container_name: account_service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      # - rabbitmq
      # - redis
    env_file:
      - ./account/.env
    networks:
      - work

networks:
  work:
    driver: bridge

volumes:
  postgres_data_test5:
