"""fix table refresh

Revision ID: 1fbcb830908e
Revises: 3325812e76ca
Create Date: 2024-12-25 16:17:05.216078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fbcb830908e'
down_revision: Union[str, None] = '3325812e76ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_session', sa.Column('reftesh_token_id', sa.UUID(), nullable=False))
    op.alter_column('refresh_session', 'reftesh_token',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_refresh_session_reftesh_token', table_name='refresh_session')
    op.create_index(op.f('ix_refresh_session_reftesh_token_id'), 'refresh_session', ['reftesh_token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_session_reftesh_token_id'), table_name='refresh_session')
    op.create_index('ix_refresh_session_reftesh_token', 'refresh_session', ['reftesh_token'], unique=False)
    op.alter_column('refresh_session', 'reftesh_token',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('refresh_session', 'reftesh_token_id')
    # ### end Alembic commands ###
