"""createre fresh table

Revision ID: 439bc58ff503
Revises: 9d6ab6f6c4e3
Create Date: 2024-11-14 02:20:55.078501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439bc58ff503'
down_revision: Union[str, None] = '9d6ab6f6c4e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_session',
    sa.Column('reftesh_token', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('expire_in', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('creates_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reftesh_token')
    )
    op.create_index(op.f('ix_refresh_session_reftesh_token'), 'refresh_session', ['reftesh_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_session_reftesh_token'), table_name='refresh_session')
    op.drop_table('refresh_session')
    # ### end Alembic commands ###
