"""update hopital model add is_deleted

Revision ID: 5408a9bb5d08
Revises: d22d9068459d
Create Date: 2025-01-18 16:32:33.545126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5408a9bb5d08'
down_revision: Union[str, None] = 'd22d9068459d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'is_deleted')
    # ### end Alembic commands ###
